### ISSUE TITLE
Port WebKit's base64 implementation to improve performance

### ISSUE THREAD

**Issue by craftzdog** [craftzdog/react-native-quick-base64#13]
It uses a lookup table
https://github.com/WebKit/WebKit/blob/main/Source/WTF/wtf/text/Base64.cpp

ref: https://github.com/margelo/react-native-quick-crypto/issues/18

**Comment by craftzdog** [comment]
other implementations:
- https://github.com/npodonnell/fast-base64
- https://stackoverflow.com/questions/180947/base64-decode-snippet-in-c

**Comment by Aure77** [comment]
Is this still planned ?

**Comment by craftzdog** [comment]
No, but there is good news: https://twitter.com/tmikov/status/1747462584725545049
So, I'm going to close this issue as not planned

**Comment by Aure77** [comment]
In my case _atob_ and _btoa_ are not useful because they don't support UTF8 encoded string (ex: `atob('5bCP6aO85by+');// expected output: 小飼弾`).
But a quick `toByteArray` function should be interested 😉
