### ISSUE TITLE
CMake blocking in build on RN 0.70

### ISSUE THREAD

**Issue by Productivix** [craftzdog/react-native-quick-base64#15]
hello, 
On RN 0.70.4
with this module , build on Window is blocking .

error message : 
`> Task :react-native-quick-base64:buildCMakeDebug[armeabi-v7a] FAILED
C/C++: ninja: error: mkdir(CMakeFiles/quickbase64.dir/myprojectpath): No such file or directory
`

**Comment by ablack34** [comment]
Hello, facing this issue, is there any workaround?

**Comment by Productivix** [comment]
hi, yes compile on Linux or may be Mac , no more problem
