### ISSUE TITLE
Calling synchronous methods on native modules is not supported in Chrome

### ISSUE THREAD

**Issue by AshlandWest** [craftzdog/react-native-quick-base64#21]
Importing atob results in a crash with the following error:
```
ExceptionsManager.js:151 Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.
```

- React Native version: 0.70.5.
- Node version: 18.14.0.
- Device: Samsung Galaxy S22 Ultra.
- Running in debug mode.
- Using expo, but prebuilt the project.

This crash happens when adding `import { atob } from "react-native-quick-base64";` and app runs fine when that line is removed.

**Comment by the-habu** [comment]
Similar problem here. Crashes with the same message when calling `shim()` in debug mode on Android. 
I have to comment it out when debugging for now.

**Comment by AshlandWest** [comment]
The issue seems to have been resolved by updating Expo CLI. I was on the latest release at the time of posting, but they released an update a bit later, and after installing, I am no longer experiencing the issue.

I have to prebuild my app because I'm using quite a few 3rd party libraries, and I chose not to fully eject.

@the-habu I'd give that a try, and if you're not using Expo, perhaps React Native CLI has a similar update you could check for. It's also worth noting that RN doesn't technically support the latest Node version, though it seems to work fine for me. Downgrading to the latest supported version might be another good step to try.
Finally, I probably should have mentioned this in the original ticket, but I'm technically not using Chrome for debugging. I use React Native Debugger, which, based on the console error, I'm guessing leans pretty heavily on the chrome codebase.

I'm going to close out this issue since I found a solution to the posted problem, but if it doesn't resolve your problem, it's probably worth creating a new issue with your details and back-linking with a comment here.
