### ISSUE TITLE
base64FromArrayBuffer is undefined

### ISSUE THREAD

**Issue by 17Amir17** [craftzdog/react-native-quick-base64#25]
Very very rarely on ios base64FromArrayBuffer is not defined, which gives the following error:

<img width="390" alt="Screenshot 2023-05-23 at 16 30 54" src="https://github.com/craftzdog/react-native-quick-base64/assets/36531255/6b40c5c7-d251-4a8b-9f73-d1258b365293">

@craftzdog @BlackCat1397 I saw you pushed a commit a few weeks ago, does this address this problem? Can you create a new release?

**Comment by ororsatti** [comment]
@craftzdog 
WDYT ?

**Comment by craftzdog** [comment]
I haven't ever reproduced it on my project
