### ISSUE TITLE
Fails to build with RN 0.74rc3

### ISSUE THREAD

**Issue by losh11** [craftzdog/react-native-quick-base64#33]
<img width="631" alt="Screenshot 2024-03-15 at 02 35 58" src="https://github.com/craftzdog/react-native-quick-base64/assets/2608570/8bdd59c6-ac8a-41cc-bf16-19d14a015f65">

I'm trying to use `react-native-quick-crypto` which has a dependency on `react-native-quick-base64`, and during a build Xcode errors with this package installed. Without this package everything seems to build as expected. As we are in a later stage release candidate for React Native, it's likely this will fail for 0.74 release too.

**Comment by craftzdog** [comment]
PR would be appreciated

**Comment by craftzdog** [comment]
can you try it again with v2.1.0?

**Comment by migueldaipre** [comment]
Fixed by #36
