### ISSUE TITLE
With version  2.0.2 getting react-native-quick-base64:generateJsonModelDebug error 

### ISSUE THREAD

**Issue by activexJ** [craftzdog/react-native-quick-base64#8]
Hi,

with the update 2.0.2 android build is failing with the following error. Can you please check

Execution failed for task ':react-native-quick-base64:generateJsonModelDebug'.
> C:\Users\aj\work\node_modules\react-native-quick-base64\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at C:\Users\aj\work\node_modules\react-native-quick-base64\android\CMakeLists.txt:14 (add_library):
    Syntax error in cmake code when parsing string

      C:\Users\aj\work\node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp

    Invalid character escape '\U'.

**Comment by craftzdog** [comment]
Can you reproduce it with [example](https://github.com/craftzdog/react-native-quick-base64/tree/master/example)?

**Comment by craftzdog** [comment]
Related: https://github.com/mrousavy/react-native-mmkv/issues/280

**Comment by ChimblesTheEternal** [comment]
> Related: [mrousavy/react-native-mmkv#280](https://github.com/mrousavy/react-native-mmkv/issues/280)

Had the same issue building windows. The solution in this thread worked for me.

**Comment by ChimblesTheEternal** [comment]
> Related: [mrousavy/react-native-mmkv#280](https://github.com/mrousavy/react-native-mmkv/issues/280)

I was experiencing the same issue on windows, but the solution in this thread worked.
